### PR TITLE
Proposal moved to https://github.com/stdgraph/P1709

### PR DESCRIPTION
**Pull request by neoblizz**

### CODE REVIEW

**Comment by neoblizz** [comment]
See: https://github.com/stdgraph/P1709

**Comment by pratzl** [comment]
That looks good in the P1709 repository. I assume you'll be removing the same files from master?

**Comment by neoblizz** [comment]
> That looks good in the P1709 repository. I assume you'll be removing the same files from master?

Yes, this PR does that for us.

**Comment by keith-bennett-airmap** [comment]
I can't see the linked P1709 repository -- Github returns 404. Is it supposed to be public?

**Comment by neoblizz** [comment]
> I can't see the linked P1709 repository -- Github returns 404. Is it supposed to be public?

It should be accessible now.

**Pull request merged**
