### PR TITLE
PageRank Algorithm Implementation + Testing improvements

### PR DESCRIPTION
**Pull request by neoblizz**

### CODE REVIEW

**Comment by pratzl** [comment]
I haven't implemented PageRank before, so I think someone else should review it for the implementation.

edge_weight_function is a common definition and should be defined in another file. I think graph.hpp would be a good location.

**Comment by neoblizz** [comment]
> I haven't implemented PageRank before, so I think someone else should review it for the implementation.
> 
> edge_weight_function is a common definition and should be defined in another file. I think graph.hpp would be a good location.

I will spend some more time on the implementation. It ended up becoming more complex since;
- It can handle dangling nodes,
- It is weighted (you can easily implement this to not consider EWF).

**Comment by neoblizz** [comment]
Improvements to testing: https://github.com/stdgraph/graph-v2/pull/41/files#diff-4461c617ceae0c7e0206622aacdf555aedd62eb129c2efb74c84fa1567bcbe0d @pratzl

**Comment by pratzl** [comment]
From our last meeting, it sounded like Andrew reviewed the PageRank code so I'm not worried about that.
I'll look at the separate unit test executables to see how to run multiple tests at once. I'll contact you separately if I run into any problems.
Thanks!

**Comment by neoblizz** [comment]
> From our last meeting, it sounded like Andrew reviewed the PageRank code so I'm not worried about that. I'll look at the separate unit test executables to see how to run multiple tests at once. I'll contact you separately if I run into any problems. Thanks!

The example is right here: https://github.com/stdgraph/graph-v2/blob/master/.github/workflows/ubuntu.yml#L45-L46

**Pull request merged**
